[package]
name = "quasi"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Polak <me@matteopolak.com>"]
description = "A slightly off-putting interpreted programming language."

[dependencies]
bytecount = "0.6"

[dependencies.clap]
version = "4"
features = ["derive"]
